version: '3.8'

# Development overrides
services:
  # Nginx - port already exposed in main config
  nginx-proxy:
    environment:
      - NGINX_DEBUG=1

  # WebApp with development settings
  webapp:
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost/api
    volumes:
      # Mount source code for live reload (uncomment if needed)
      # - ./webapp/src:/app/src
      - ./logs/webapp:/var/log/webapp
    ports:
      - "3000:3000"  # Optional: direct access to webapp for debugging

  # API with development settings
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      # Mount source code for live reload (uncomment if using dotnet watch)
      # - ./api/src:/app/src
      # - ./api/appsettings.Development.json:/app/appsettings.Development.json
      - ./logs/api:/app/Logs
    ports:
      - "5000:5000"  # Expose API for direct access/Swagger in development