version: '3.8'

services:
  # Nginx Reverse Proxy (Shared for WebApp + API)
  nginx-proxy:
    build: ./nginx
    container_name: ollo-nginx-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL certificates (read-only)
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # WebApp Service
  webapp:
    build: .
    image: dayandev/ollolifestyle-webapp:latest
    container_name: ollo-webapp
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://127.0.0.1:5000
    volumes:
      - ./logs/webapp:/var/log/webapp
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



networks:
  frontend:
    driver: bridge

volumes:
  logs:
    driver: local