version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx-proxy:
    build: ./nginx
    container_name: ollo-nginx
    restart: unless-stopped
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # WebApp Service
  webapp:
    build: .
    container_name: ollo-webapp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://nginx-proxy/api
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  frontend:
    driver: bridge

volumes:
  logs:
    driver: local