name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: |
          dayandev/ollolifestyle-webapp:latest
          dayandev/ollolifestyle-webapp:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 10m
        fingerprint: SHA256:ZIINJvcZVuk5x/80mfCBiPf+WhwYbY0k/ovG0d6po/A
        script: |
          cd ~/OlloLifestyle.WebApp
          git pull origin main
          docker build --no-cache -t dayandev/ollolifestyle-webapp:latest .
          docker-compose down
          docker-compose up -d